name: dsp_app
description: ESP32 DSP Controller
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
